name: Initialize

on:
  push:
    branches:
      - main

jobs:
  initialize:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
      - uses: actions/setup-node@v3
        with:
          node-version: 21
      - run: git pull

      - name: Run replace-all-words
        run: npx replace-all-words ./ 'template-typescript' "${{ github.event.repository.name }}"
        if: ${{ github.event.repository.name }} != 'template-typescript'
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'autogen: replace template with repository name and remove initialize / npx replace-all-words ./ template-typescript ${{ github.repository }}'

      - name: Remove job for initialize
        run: rm .github/workflows/initialize.yml
        if: ${{ !startsWith(github.event.repository.name, 'template-') }}
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'autogen: remove job for initialize / rm .github/workflows/initialize.yml'

      - name: Trigger repository-management
        if: ${{ !contains(github.event.repository.name, 'template') }}
        run: |
          curl -X POST -f -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
               -H "Accept: application/vnd.github.v3+json" \
               "https://api.github.com/repos/HiromiShikata/repositories-management/actions/workflows/repositories-management.yml/dispatches" \
               -d '{
                 "ref": "main",
                 "inputs": {
                 }
               }'
